language: ruby
cache:    bundler
rvm:
  - 2.3.1
sudo: false
script:
  - bundle exec foodcritic -f any . -X spec
  - bundle exec rspec --color --format documentation
branches:
  only:
    # Only build mainline branches - anything else will be picked up by the PR builder
    # Prvents Travis building PR branches twice
    - /^[0-9\.]+\.x$/
