language: ruby
rvm:
  - 1.9.3
sudo: false
addons:
  apt:
    packages:
      - libgecode-dev
env: USE_SYSTEM_GECODE=1
script: 
  - bundle exec foodcritic -f any .
  - bundle exec rspec --color --format progress
