dist: trusty
language: ruby
cache:    bundler
rvm:
  - 2.4
sudo:     false
gemfile:
  - Gemfile
before_install:
  - gem install bundler
script:
  # Skip FC061 to allow x.y.z-pre etc versions during development
  - bundle exec foodcritic . -t ~FC061
  - bundle exec rspec --color --format documentation
branches:
  only:
    # Only build mainline branches - anything else will be picked up by the PR builder
    # Prvents Travis building PR branches twice
    - /^[0-9\.]+\.x$/
